Grpc:
  server.port: 50051
Dashboard:
  service.port: 9999
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30
Api:
  service.port: 9998
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30
  